cart/urls.py
from .import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
    ]
# path('buy/<int:product_id>/',views.buy,name='buy'),

login/urls.py
from .import views
from django.urls import path

app_name='login'

urlpatterns = [
    path('register',views.register,name='register'),
    ]

search_app/urls.py
from .import views
from django.urls import path

app_name='search_app'

urlpatterns = [
    path('',views.searchResult,name='searchResult'),
    ]

shopping/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shoppingapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('login/',include('login.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shoppingapp/urls.py
from .import views
from django.urls import path

app_name='shoppingapp'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),
]

cart/models.py
from django.db import models
from shoppingapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return '{}'.format( self.product)

login/models.py
from django.db import models

# Create your models here.

search_app/models.py
from django.db import models

# Create your models here.

shoppingapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shoppingapp:products_by_category',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    update=models.DateField(auto_now=True)

    def get_url(self):
        return reverse('shoppingapp:prodCatdetail',args=[self.category.slug,self.slug])
    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shoppingapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item =CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items = cart_items,total = total,counter=counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

login/views.py
from django.shortcuts import render

# Create your views here.
def register(request):
    return render(request,"register.html")

search_app/views.py
from django.shortcuts import render
from shoppingapp.models import Product
from django.db.models import Q
# Create your views here.

def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

shoppingapp/views.py
from django.shortcuts import render,get_object_or_404
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def allProdCat(request, c_slug=None,):
    c_page = None
    products_list = None
    if c_slug !=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list =Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list =Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,3)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescrition %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet"href="{% static 'css/custom.css' %}"  >
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
{% include 'header.html' %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--        <li class="nav-item">-->
<!--            <a class="nav-link" href="{%url 'shoppingapp:allProdCat' %}"></a><a><img src="{% static 'img/logo.png'%}" alt="image loading" width="120px" height="80px"></a>-->
<!--        </li>-->

        <li class="nav-item">
          <a class="nav-link" href="{% url 'shoppingapp:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shoppingapp' in request.path %} active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shoppingapp:allProdCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the cart page. Proceed to review your items and place the order
{% endblock %}

{% block title %}
    cart -NR shop
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart is empty</h1>
        <br>
        <p class="text-center">Please Select <a href="{% url 'shoppingapp:allProdCat' %}">From Here</a> </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart</h1>
        <br>
    </div>
</div>
<br>
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12  col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my-custom_thead">
                <tr>
                    <th colspan="10">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" style="width:100px;height:100px;"  class="float-left rounded custom_image"></a>

                </td>
                <br>
                <td class="text-lef">
                    <br>
                    <h6>{{cart_item.product.name}}</h6>
                    <br>
                     SKU: {{cart_item.product.id}}
                    <br>
                    Price: Rs {{cart_item.product.price}}
                    <br>
                    Qty: {{cart_item.quantity}} x Rs {{cart_item.product.price}}
                </td>
                <td>
                    Rs {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                     <td>
                         &nbsp;<a class="custom_icon" href="{% url 'cart:add_cart' cart_item.product.id %}" > <i class="fas fa-plus  "> </i> </a>
                         &nbsp;<a class="custom_icon" href="{% url 'cart:cart_remove' cart_item.product.id %}" ><i class="fas fa-minus "> </i></a>
                         &nbsp;<a class="custom_icon" href="{% url 'cart:full_remove' cart_item.product.id %}" ><i class="fas fa-trash "> </i></a>
                     </td>
                {% else %}
                    <td>
<!--class="custom_a"-->
                         &nbsp;<a class="custom_icon" href="{% url 'cart:cart_remove' cart_item.product.id %}"> <i class="fas fa-minus "> </i> </a>
                         &nbsp;<a class="custom_icon" href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fas fa-trash "> </i></a>
                     </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12  col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my-custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
        </thead>
        <tbody>
        <tr>
            <td class="text-left">
                Please review your shopping cart items before proceeding with the order payment

            </td>
        </tr>
        <tr>
            <td class="text-left">
                your Total is : <strong>{{ total }}</strong>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="row mx_auto">
        <a href="{% url 'shoppingapp:allProdCat' %}" class="btn btn-warning  my_custom_button">Continue Shopping</a>
        <a href="{% url 'shoppingapp:allProdCat' %}" class="btn btn-success  my_custom_button">Buy</a>
    </div>
{% endif %}

{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:150 }}
    {% else %}
        Welcome to NR store where you can buys different items.....
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - See our products items.....
    {% else %}
        NR traders shop
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
            <h3>Our products</h3>
        </div>
    </div>
</div>
    {% endif %}

<div>
    {% if category %}
        <center><img src="{{category.image.url}}"alt="{{category.name}}"width="1400px" height="380px" ></center>
</div>
    <br>
<div>
    <h1 class="text_center my-title">{{Category.name}}</h1>
    <p class="text_justify">{{Category.description}}</p>
</div>
    {% else %}
<div>
<img src="{% static 'img/banner1.jpg' %}" alt="NR tea, spices and nuts" width="1500px" height="250px">
</div>
<br>
<div>
    <h1>Our products collection</h1>
    <p>Cotrary to popular indian product tea, spices,nuts,dry fruits</p>
</div>
   {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-6 col-sm-9 col-md-4  col-lg-4">
            <div class="card" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" ></a>
                <div class="card-body"><h3 class="text-center">{{product.name}}</h3>
                    <h4 class=" text-center">{{product.price}}</h4>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm{% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

templates/footer.html
<br><br><br><br>
<!-- Footer -->
<footer class="page-footer font-small special-color-light pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> NR Traders.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/header.html
{% load static %}
<header>
     <center>
       <h1><a href="{%url 'shoppingapp:allProdCat' %}"></a> <img src="{% static 'img/logo.png'%}" alt="image loading" width="90px" height="80px">NR TRADERS</h1>
    </center>
</header>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:150 }}



{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} -NR traders shop

    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}"alt="{{product.name}}" width="350" height="330">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_tittle">{{product.name}}</h1>
            <p>Rs{{product.price}}</p>
            <h4 class="my_tittle">Product Description</h4>
            <p class="text-justify my-rod-text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my-prod-text"><b>Out of stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}

        </div>
        </div>
</div>
    </div>
</div>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
test register
</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescrition %}
   We have variety of products .
{% endblock %}
{% block title %}
    Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text"> You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width:20rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my-image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h3>{{product.name}}</h3>
                    <h4>{{product.price}}</h4>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"> 0 results found </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}